### ISSUE TITLE
Get machinekit running with stepper motors

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/Tosca#1]
Using @goatchurchprime's spare Beaglebone with Machinekit on it, hook it up to @DefProc's TLRN stepper motors and get it moving around with gcode.

**Comment by DefProc** [comment]
Sounds cool, there's some NEMA23s in my box in the workshop, or some 17s in
the flight case in new dinky stores. They should both have spools attached,
but the mounts for the 17s are a bit better.

**Comment by amcewen** [comment]
There's only one stepper in the flight case

**Comment by amcewen** [comment]
But that's because we'd already borrowed two from it to try hooking up to machinekit :-D

**Comment by DefProc** [comment]
:O

**Comment by goatchurchprime** [comment]
Now runs reliably with manual homing and gcode
