### ISSUE TITLE
Can we draw a map with it

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/Tosca#20]
Need to get the openstreetmap data and the area of Liverpool that we want to draw, and process it into SVG and gcode.

**Comment by goatchurchprime** [comment]
Please submit an SVG of the map here

**Comment by amcewen** [comment]
I've created an Examples directory, and stuck an example SVG of the centre of Liverpool into it - https://github.com/DoESLiverpool/Tosca/blob/master/Examples/Liverpool_city_centre.svg

**Comment by amcewen** [comment]
From Lizzie:

"the area for the map will need to be between Lodge Lane in L8 and Upper Duke Street. We only need to show Upper Duke Street as far as the Anglican Cathedral but it'd be great to get the whole of Lodge Lane in. It's also important that Hope Street's on there."

So that's what we'll need to generate for the performance.

**Comment by amcewen** [comment]
From Lizzie:

"the area for the map will need to be between Lodge Lane in L8 and Upper Duke Street. We only need to show Upper Duke Street as far as the Anglican Cathedral but it'd be great to get the whole of Lodge Lane in. It's also important that Hope Street's on there."

So that's what we'll need to generate for the performance.

**Comment by amcewen** [comment]
Can we draw a map with it?  We can.  And we did!
