### ISSUE TITLE
Get some pens that can draw on windows

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/Tosca#22]
The stepper-based version is going to draw on the inside of a window (so passers-by can see it - and maybe even interact with it).  So we need to get some pens that can draw on the window (and that can be cleaned off afterwards too :-)

**Comment by JackiePease** [comment]
'll try to get some scraps of black foamcore or correx to try them out on too

**Comment by amcewen** [comment]
There is a spare glass bed for the RepRap that I'm sure we could try, and I guess there'll be plenty of glass bottles in the recycling for initial "does this write on glass, and can we clean it off?" testing :-)

Plus some windows in Dinky and the main office that we can try rigging it up onto...

**Comment by JackiePease** [comment]
I have bought some pens. Currently at DoES so hopefully will be able to try them out later.

**Comment by amcewen** [comment]
Cool.  The RepRap glass is in the 3d printing supplies cupboard under the printers, if you want that to try out.

I've got some stuff to do, but should be in DoES around 3ish

**Comment by JackiePease** [comment]
Chalk markers do write on glass
