### ISSUE TITLE
Laser-etch a credits file for Knut

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/Tosca#36]
It'd be nice to have a small board (A5-ish) to lean against the window that Knut is drawing on to explain a little what it is (or at least point people at where it was made).

Something along the lines of the DoES Liverpol logo, the name of the "Knut Polargraph" as a heading, and then the content of https://github.com/DoESLiverpool/Tosca/blob/master/Credits.md below

**Comment by JackiePease** [comment]
Knut has been retired - open new issue to produce something similar for Liverpool MakeFest
